# Generated by Django 5.2 on 2025-04-29 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ddc",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
